{% set name = "lbplatformutils" %}
{% set version = "4.3.15" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/lbplatformutils-{{ version }}.tar.gz
  sha256: 3b3b1a823911890b0f4a320db6ec887707fdb5bb698353f8e6765c1c237d4199

build:
  number: 0
  noarch: python
  entry_points:
    - lb-debug-platform = LbPlatformUtils.debug:main
    - lb-describe-platform = LbPlatformUtils.describe:main
    - lb-host-binary-tag = LbPlatformUtils.describe:host_binary_tag_script
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python !=3.0,!=3.1,!=3.2,!=3.3
    - poetry
  run:
    - python !=3.0,!=3.1,!=3.2,!=3.3

test:
  imports:
    - LbPlatformUtils
  commands:
    - pip check
    - lb-debug-platform --help
    - lb-describe-platform --help
    - lb-host-binary-tag --help
  requires:
    - pip

about:
  home: https://gitlab.cern.ch/lhcb-core/LbPlatformUtils
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: utilities from platform detection
  doc_url: https://gitlab.cern.ch/lhcb-core/LbPlatformUtils
  dev_url: https://gitlab.cern.ch/lhcb-core/LbPlatformUtils

extra:
  recipe-maintainers:
    - chrisburr
